# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pre-requisites
      run: |
        cd /home/runner/work/bbn-i2c-over-usb/bbn-i2c-over-usb
        git submodule update --init --recursive
        make
